### ISSUE TITLE
Feature requests/Bug report link on wiki, & outdated discord ID

### ISSUE THREAD

**Issue by Xinnoh** [zkldi/Tachi#1072]
I was looking for a way to make a feature suggestion, but there's no info that this github exists on the wiki. It's only in the api & codebase reference which most people won't look at. It would be sensible for the wiki to link here if the user has a feature request or a bug report.
Also adding other links to stuff like the ko-fi and whatnot would make sense, didnt know it existed until looking through the github

Edit: I went through the site a bit more and some of that stuff is already there.
I wasn't able to find it because it was in the "Getting Started" panel, which I avoided because I thought it was a setup guide for people who are yet to set up the program, I was only looking through the wiki.
Renaming the Getting Started section to Documentation would probably make sense.

Also
https://docs.tachi.ac/api/
"If you are in a scenario where you might be hitting even 100 requests a minute consistently, please contact me at zkldi#2965"
discord IDs were changed so this no longer works.

**Comment by zkldi** [comment]
I've cleaned this up and hopefully made this more obvious now. Let me know what you think.

**Comment by Xinnoh** [comment]
i don't think the change was uploaded
the discord id is still the old version so that's probably the case
