### ISSUE TITLE
Maimai Dx Jp server import

### ISSUE THREAD

**Issue by Xinnoh** [zkldi/Tachi#1080]
https://replit.com/@sinnohosu/Maimai-Importer-Kamaitachi?v=1

Imported scores example: https://kamai.tachi.ac/u/Sinnoh/games/maimaidx/Single

I created a scuffed but working importer that works for Jp/Cn/Int. I can't add it to the site since idk how web dev works.
I couldn't get the existing international importer to work, so this also works there as an alternative.

If this code can be moved to something better I'm all for it.

**Comment by zkldi** [comment]
You can use `"matchType": "songTitle"` to match on songTitle instead of looking up song titles yourself. That should save you quite a bit of work in the script.

You could rewrite this in javascript and make it part of the bookmarklet. It shouldn't be too hard, chatGPT can probably get you 50% of the way and if you ask in KT #dev they'll help you out.

I don't know who wrote the original intl importer, @j1nxie perhaps? It should work, if it doesn't that's a problem.

**Comment by Xinnoh** [comment]
the international importer seems to work fine for most people, mine might not be working because it's a really old account that hasn't been played in years
I changed the script to match songTitle, should be more future proof.
Javascript is fine but bookmarklets and stuff are a bit outside my comfort zone so I don't really want to do more beyond that. I'm fine if someone wants to modify it to use on their own site.

**Comment by beerpiss** [comment]
The international importer can be made to work with the Japanese maimai DX NET with minimal code changes. I'm not sure if maimai locks play details (judgements, etc.) behind a standard course subscription like CHUNITHM does, but that was the biggest change I had to do to make the CHUNITHM site importer compatible with the JP website.

https://github.com/beerpiss/kt-chunithm-site-importer/commit/6bef40a3c279588c8102eafc144c4d02eb7b6757

**Comment by j1nxie** [comment]
> The international importer can be made to work with the Japanese maimai DX NET with minimal code changes. I'm not sure if maimai locks play details (judgements, etc.) behind a standard course subscription like CHUNITHM does, but that was the biggest change I had to do to make the CHUNITHM site importer compatible with the JP website.
> 
> [beerpiss/kt-chunithm-site-importer@6bef40a](https://github.com/beerpiss/kt-chunithm-site-importer/commit/6bef40a3c279588c8102eafc144c4d02eb7b6757)

it does gate play details behind standard course like CHUNITHM, yeah.

@beerpiss has also submitted a PR onto my intl importer that supports JP imports as well.

**Comment by Xinnoh** [comment]
if support is coming in the future then this can probably be closed then
