### ISSUE TITLE
MYT uploads are timestamped in the future

### ISSUE THREAD

**Issue by nyairobi** [zkldi/Tachi#1087]
Both Tunism and Ongeki.

An example (these are not fresh scores; the offset is probably JST-UTC as usual):

![image](https://github.com/zkldi/Tachi/assets/61069237/62372d45-51b7-411b-a47b-c4cbc6f7cf83)

**Comment by zkldi** [comment]
@albshin This is a must fix. Please fix this mythos-side.

**Comment by albshin** [comment]
Also affects WACCA, @GRIM657 will be taking charge in fixing
