### ISSUE TITLE
Reverting an import for a chart hides all your scores of that chart

### ISSUE THREAD

**Issue by nyairobi** [zkldi/Tachi#1129]
### Steps to reproduce

1. Have at least one existing score on a chart.
2. Make an import with a new score of that chart.
3. Revert that import.

#### Expected behavior
Only the new score gets reverted.

#### Actual behavior 
It appears as if I haven't ever played the chart, and my NaiveRating drops down (even though it's only supposed to go up). This is my real graph for Ongeki:

![Screenshot_20240718_004513](https://github.com/user-attachments/assets/6c4de93f-9b0d-4401-9ae2-8e6cd1ce2389)

Furthermore, adding another import for that chart fixes it.

### Minimal example

1. Import [test1.json](https://github.com/user-attachments/files/16275531/test1.json).
2. Import [test2.json](https://github.com/user-attachments/files/16275532/test2.json).
3. Revert test2.
4. Go [here](https://staging.tachi.ac/games/chunithm/Single/songs/2100/EXPERT) and note you're not there.
5. Import [test3.json](https://github.com/user-attachments/files/16275533/test3.json).
6. Go back to the chart page and note that the score from test1 has re-appeared.

**Comment by zkldi** [comment]
I suspect this is an issue with the PB logic somehow. Maybe the PB on the chart is getting removed.
